### ISSUE TITLE
LayeredMap zoom level resets on single mouse-click

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#101]
Zoom level currently resets on single mouse click / hold.
This behaviour should be limited to double mouse-click so that panning and drawing of polylines can be done without resetting the view.

**Comment by anders-kiaer** [comment]
It appears to be due to [this](https://github.com/equinor/webviz-subsurface-components/blob/master/src/lib/components/LayeredMap.js#L172-L175) check. `componentDidUpdate` is called automatically `onClick`, and since (typically) `uireivision` default value `''` is not overridden by component users, it calls `resetView()`.

@HansKallekleiv Should we remove the first part of the `if` expression, thereby requiring `uireivision` to actually change?

**Comment by HansKallekleiv** [comment]
As the component can be mounted with `layers = []` I don't think we can't just remove the `if` expression? We would then need to either require initial `layers` or require the use of `uirevision`.

Perhaps a quick fix is to only  call `resetView` if the `layers` prop changes?

Something like:
```javascript
    componentDidUpdate(prevProps) {
        if (
            (this.props.uirevision === "" && this.props.layers !== prevProps.layers) ||
            this.props.uirevision !== prevProps.uirevision
        ) {
            this.resetView();
        }
    }
```
