### ISSUE TITLE
Shaky DeckGL component due to overflow

### ISSUE THREAD

**Issue by SteffenEq** [equinor/webviz-subsurface-components#1181]
Overflow in DeckGL (due to e.g. hoverdata) introduce momentarily scroll bars, causing the layout to "shake".  It would be nice to e.g. disable scrollbars to avoid this.

How to reproduce (see figure below):
- Go to static storybook
- Open DeckGL map -> Wells Layer -> Default
- Move map so that pie reaches border of map
- Hover over pie

![image](https://user-images.githubusercontent.com/107108124/188407972-2689b2f1-50ba-49a6-8020-f25cd5ee9e7a.png)

**Comment by anders-kiaer** [comment]
Could perhaps be solved by adding a line of CSS (`overflow: visible`)? https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by SteffenEq** [comment]
You're right, setting `overflow: hidden` to the containing div worked well in my case (avoiding scrollbars in any case). Perhaps not an `wcc.DeckGLMap` issue after all? My bad.

**Comment by shadab-skhan** [comment]
I think handling overflow in the parent div of DeckGLMap is the best way as the parent div is aware of the viewport size by initialization.

When I handle the overflow internally in the DeckGLMap component, it doesn't work as expected. That's because, Initially when the map is loaded, the size of the viewport is not known, and it expands the viewport when it's loaded. Due to this the overflow effect is only seen on the initial viewport size.
