### ISSUE TITLE
PieChartLayer does not work

### ISSUE THREAD

**Issue by oysteinequinor** [equinor/webviz-subsurface-components#1283]
Updating from `0.4.14` to `0.4.15a2` breaks PieChartLayer. The layer does not render at all.

console in the browser:
> deck: initialization of PieChartLayer({id: 'layer1'}): Invalid number NaN

Reproducing example using `0.4.15a2`: (works on `0.4.14`)

```python
import dash
import webviz_subsurface_components


app = dash.Dash(__name__)


layers = [
    {
        "@@type": "PieChartLayer",
        "id": "layer1",
        "data": {
            "pies": [
                {
                    "x": 1,
                    "y": 1,
                    "R": 0.2,
                    "fractions": [
                        {"idx": 0, "value": 95},
                        {"idx": 1, "value": 4},
                    ],
                },
            ],
            "properties": [
                {"color": [255, 0, 0], "label": "aaa"},
                {"color": [0, 255, 0], "label": "bbb"},
            ],
        },
    }
]

views = {
    "layout": [1, 1],
    "showLabel": False,
    "viewports": [{"id": "view_1", "show3D": False, "layerIds": ["layer1"]}],
}

map_id = "asdf"
app.layout = webviz_subsurface_components.DeckGLMap(
    bounds=[0, 0, 2, 2],
    id=map_id,
    layers=layers,
    views=views,
)


app.run_server("0.0.0.0", 5000)
```

**Comment by anders-kiaer** [comment]
Thanks for the report @oysteinequinor. I guess this is related to the change in https://github.com/equinor/webviz-subsurface-components/pull/1266 where it was requested to specify pie chart radius in pixels (to keep it static independent of zoom level).

I see the example snippet uses `R=0.2`. Assuming `R` now is defining radius in pixels (correct @nilscb?), could you try to set it to some integer `R=10` @oysteinequinor and see if you get the same warning?

**Comment by oysteinequinor** [comment]
Changing radius to `10` produces the same error.

**Comment by anders-kiaer** [comment]
I see now that this apparenly has been observed randomly in the nightly scheduled tests: https://github.com/equinor/webviz-subsurface-components/actions?query=event%3Aschedule.

**Comment by nilscb** [comment]
I also see this happens sometimes in the tests. How can it fail only sometimes??
I am so far not able to reproduce it locally which is very strange.

**Comment by anders-kiaer** [comment]
> I am so far not able to reproduce it locally which is very strange.

Using the Python snippet above, it also works as expected on your side (using `0.4.15a2` or `master`)? It sounds like in @oysteinequinor example it seems to be a stable error 😄

**Comment by SteffenEq** [comment]
Flaky here as well. I suddenly had statically sized piechart (i.e. working) here for some time, but they disappeared ("Invalid number NaN" etc.) when I refreshed the browser.

**Comment by oysteinequinor** [comment]
Does not work in newly released `0.4.15a3`. Same error. But it does work in Debug mode for some reason.

**Comment by nilscb** [comment]
This dash example works fine on my windows machine. Do you use linux?

**Comment by oysteinequinor** [comment]
I am running the server on Linux. It does not work no matter if I access this server from Linux or Windows, or with Firefox or Chrome.

**Comment by SteffenEq** [comment]
Tried running @oysteinequinor's example on windows. No pies

**Comment by oysteinequinor** [comment]
Regarding the relevant test case: It might be that you need to wait until the page has completed loading with an explicit wait command, or a sleep.
https://github.com/equinor/webviz-subsurface-components/blob/287102005f7f45c66bb6f172d51328a5390ec029/tests/test_deckgl_map.py#L25

**Comment by anders-kiaer** [comment]
I'm able to reproduce this with Python 3.8. 

I went into unknown territory (TypeScript - good learning experience though) and as far as I can see there, using @oysteinequinor example snippet it fails when calculating the distance `d` on line 82 https://github.com/equinor/webviz-subsurface-components/blob/96f736392d7fca511cce35d6110ec4e704e2f9ac/react/src/lib/components/DeckGLMap/layers/piechart/pieChartLayer.ts#L73-L82 which again fails because the vectors `v1` and `v2` both have `undefined` as value for the third dimension in this case.

If I do this small change, flipping when giving 2D/3D vectors
```diff
- const p1 = is_orthographic ? [0, 0, 0] : [0, 0];
- const p2 = is_orthographic ? [npixels, 0, 0] : [npixels, 0];
+ const p1 = is_orthographic ? [0, 0] : [0, 0, 0];
+ const p2 = is_orthographic ? [npixels, 0] : [npixels, 0, 0];
```
it works as expected as far as I can see for the given snippet. Does orthographic imply two dimensional view, such that the above change makes sense?

**In order to ensure this error is picked up in the tests:** In the existing `test_deckl_map.py` we should ideally wait for the loading to be completed, but not longer. There are utilities in https://dash.plotly.com/testing#browser-apis to wait on certain HTML elements to exist, but this might not be possible to use here since I guess `deck.gl` renders most/all things in a `<canvas>` ? Maybe we simply have to sleep for some seconds to routinly catch this... (Funny enough the [scheduled test runs have been stable ](https://github.com/equinor/webviz-subsurface-components/actions?query=event%3Aschedule.) so far after #1285). 

**Unrelated question:** Using the Python example snippet in this issue, `is_orthographic` is calculated as `false` (because `this.context.viewport.constructor.name === "u"`). Shouldn't `is_orthographic` be `true` since `"show3D": False`?

**Comment by nilscb** [comment]
This makes very much sense! I have seen from before that in 2d
(orthograhic) there should only be 2 coordinates.
But in these tests I made the mistake of switching them. So your fix makes
it correct again.
I was planning to look into this tomorrow but no need for that then I guess
:-)

**Comment by nilscb** [comment]
Also yes; If show3D is set to false then is_orthographic should be true. So this test is obviously not 100%. It has to be looked into.

**Comment by anders-kiaer** [comment]
Confirmed that it works now with `debug=False` (which is the default + production setting). However with `debug=True` the problem reappears. The difference with `debug=False/True` is if minified code is used or not. I think this is basically a symptom of #1295, will follow this up there.
