### ISSUE TITLE
[NGRM] - Provide an option to hide primary scale, readout and zoom for well log component, and also option to disable right click context menu 

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1702]
We would like primary scale, legend and zoom display of the log component to be optional such that it would be possible to display the log tracks only
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/2e835af1-ab89-421e-bb83-7d0f72ee24da)

**Comment by Vladimir-Kokin** [comment]
[WellLogView (WellLogViewWithScroller) component is a central part of WellLogViewer component.
![изображение](https://github.com/equinor/webviz-subsurface-components/assets/86053741/c3ac88e7-5b7d-48ae-be33-26012fefe509)](https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/docs/welllogviewer-overview--docs)

So if only the central part without any additional UI is needed [WellLogView (WellLogViewWithScroller)](https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/welllogviewer-components-welllogviewwithscroller--default) would be used instead of WellLogViewer.
Props of these components are basicaally the same.  
WellLogViewerProps is based on WellLogViewProp type and only has some additional prop for readout options

A full customization of WellLogViewer component layout will be done with PR https://github.com/equinor/webviz-subsurface-components/pull/1363

**Comment by Midtveit** [comment]
And also add flag to disable right click context menu on log header also for synced log viewer

**Comment by Vladimir-Kokin** [comment]
@mirisb, It seems the issue could be closed as implemented with #1363
