### ISSUE TITLE
[NGRM] - silent crash when displaying Grid 3D

### ISSUE THREAD

**Issue by w1nklr** [equinor/webviz-subsurface-components#2077]
Grid3DLayer crashes silently when trying to display a big grid.

The crash (out of memory) occurs in a webworker when building the GL friendly data from the input data.
Possible fix can be to perform the computation chunk-wise and send back each chunk to the main thread that has to glue them together.

**Comment by LeonidPolukhin** [comment]
The task is capacious so should be devided into the following stages:
1) Reduce memory usage in the webworker.  GL data is computed filling JS native arrays and next is copied into output typed arrays. Instead of that. the webworker could compute GL data in typed arrays directly.
2) Webworker's input and output typed arrays are not transferred but cloned. 
3) Chunk-wise GL data computing.
