### ISSUE TITLE
run example failed

### ISSUE THREAD

**Issue by yejiyang** [equinor/webviz-subsurface-components#67]
Hi, 

When I test out the example case, I got the following error when I open the url http://127.0.0.1:8050/. 

Any suggestions on how to fix it?

Thanks,
Jiyang

error info:

Invalid argument `data` passed into HistoryMatch with ID "parameters".
Expected `object`.
Was supplied type `string`.
Value provided: "{\"iterations\": [{\"name\": \"Iteration   ......

**Comment by anders-kiaer** [comment]
Hi @yejiyang. Thanks for repoting this. Looks like `npm start` and running the JavaScript visualization (i.e. outside Python) works, but not the Python example `examples/example_hm.py` where I am able to reproduce your error.

**Comment by yejiyang** [comment]
The fix works! @anders-kiaer  Thanks! 
The following libraries need to be installed. 
`pip install numpy scipy matplotlib pandas Pillow`

**Comment by anders-kiaer** [comment]
Thanks @yejiyang.

> The following libraries need to be installed.
> `pip install numpy scipy matplotlib pandas Pillow`

Those example dependencies should definitely be added somewhere, not exactly sure where though. 
`webviz_subsurface_components` itself does not depend on them, but you will likely want to install one or more of them in order to create the input data necessary. I guess there are thee main possibilites:

1) Add them to [`install_requires`](https://github.com/equinor/webviz-subsurface-components/blob/60973c1bb6a1ae411c807b47ba2091380cd21a95/setup.py#L14) such that they are installed when doing `pip install webviz_subsurface_components` - even though they are not strictly dependencies.
2) Add them to [`tests_requires`](https://github.com/equinor/webviz-subsurface-components/blob/60973c1bb6a1ae411c807b47ba2091380cd21a95/setup.py#L16) such that they are installed when running `pip install webviz_subsurface_components[tests]`.
3) Creating a new group of extra dependencies, such that they are installed when running e.g. `pip install webviz_subsurface_components[examples]`.

I am leaning towards 2) for now. It might be that we later want to add some helper function within `webviz_subsurface_components` to create the necessary component input from Python structures (e.g. dataframes) - then they turn to actual dependencies.

**Comment by anders-kiaer** [comment]
Example dependencies now added to `tests_requires` in [this commit](https://github.com/equinor/webviz-subsurface-components/pull/68/commits/ecb8cedcbaf1f39e4e7c977ae0203636ba10faa9).
