### ISSUE TITLE
using addon-redux enforces dependency on @storybook in production

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#720]
addon-redux is a Storybook addon that helps when building stories using components that use redux state.
It should not be used in files which are part of the final package especially in production and on web applications

@ ./node_modules/addon-redux/dist/esm/index.js 8:0-57 8:0-57
 @ ./node_modules/@webviz/subsurface-components/dist/components/DeckGLMap/redux/store.js

**Comment by anders-kiaer** [comment]
Thanks for the issue report @mirisb - and agree with you, it feels strange to have it in dependencies (being a storybook addon). We moved it from `devDependencies` to `dependencies` in #539 in order to solve #523, but I'm unsure why #523 appeared in the first place. @t0oF @hkfb Do you have any new insight into why #523 appeared?

**Comment by t0oF-emr** [comment]
#523 (ie. the dependency on addon-redux) was always there. We were the first ones to use subsurface-components as an npm dependency, which is why I filed the issue.

**Comment by t0oF** [comment]
BTW, I just created a PR #722 to remove test and storybook related files from the generated package. This PR does not fix the current issue though.
