### ISSUE TITLE
Toggling any layer triggers reloading of other layers

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#766]
For example, toggling the drawing layer causes the property layer to reload the property data.

**Comment by shadab-skhan** [comment]
The issue is in Map3DLayer where if you perform any action on the toolbar, the depthMap.png and property_margin_10pt.png get reloaded (can check on network console of the debugger).

Also if you add console log on TerrainMapLayer::render(), it's getting called multiple times even if you hover on the map.

https://deck.gl/docs/developer-guide/performance
