### ISSUE TITLE
CSP issues with the `TerrainLoader` used by `Map3DLayer`

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#835]
The Map3DLayer loads the [TerrainLoader](https://loaders.gl/modules/terrain/docs/api-reference/terrain-loader) dynamically from `https://unpkg.com/@loaders.gl/terrain@3.1.8/dist/terrain-worker.js`.
This causes [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) issues when used in Webviz, and the data is not loaded.
(We aim to control and reduce external connections due to security concerns.)

Solutions:
1. Serve the worker code locally: https://deck.gl/docs/developer-guide/loading-data#loaders-and-web-workers
2. Import the worker code directly
3. Add an exception in Webviz CSP allowing the worker code to be downloaded dynamically

Thoughts? (@akia) 

Example of console error:
```
       Refused to load the script 'https://unpkg.com/@loaders.gl/terrain@3.1.8/dist/terrain-worker.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by anders-kiaer** [comment]
I guess we want to avoid it running on the main thread (i.e. use web worker), and also avoid CSP exception for CDN (i.e. that we control the hosting of the `.js` file). So that would be option 1)? I guess we then want the file to be served through `webviz-subsurface-components` to keep the JavaScript logic contained in that repository. Maybe we also can point to the self-served file directly using something like https://stackoverflow.com/questions/6042007/how-to-get-the-host-url-using-javascript-from-the-current-page to find the same host of the main JavaScript bundle such that it works without any configuration by the consumer 🤔

**Comment by hkfb** [comment]
As long as we ensure that the terrain calculation does not lock the main thread for too long, I think option 2) should work.

**Comment by anders-kiaer** [comment]
There is some history to this "problem" here apparently: https://stackoverflow.com/questions/5408406/web-workers-without-a-separate-javascript-file

**Comment by hkfb** [comment]
Can we encode the external script in a data URL? https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by anders-kiaer** [comment]
That is a possibility we could try. Maybe then use `blob:` instead of `data:` as protocol?

Snippet from Mozilla's documentation (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources):

> _<scheme-source>_
> A scheme such as _http:_ or _https:_. The colon is required. Unlike other values below, single quotes shouldn't be used. You can also specify data schemes (not recommended):
> 
> * _data:_ Allows [data: URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.
> * _mediastream:_ Allows [mediastream: URIs](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API) to be used as a content source.
> * _blob:_ Allows [blob: URIs](https://developer.mozilla.org/en-US/docs/Web/API/Blob) to be used as a content source.

To my knowledge, the reason Mozilla's documentation doesn't have the same explicit warning for `blob:` is due to the fact that `blob:` URLs can only be generated internally by the browser (while `data:` URLs can be crafted externally). I _think_ also a blob URL only have scope equal to the origin/page it was created on.

`.toBlob` compared with `.toDataURL` [appears to also have other benefits](https://stackoverflow.com/questions/59020799/which-function-should-i-use-todataurl-or-toblob).

Even with `blob:` we probably will "force" the downstream users to include `blob:` in their CSP `script-src` settings, which might be ok 🤔
