### ISSUE TITLE
DeckGLMap component is miss-aligned

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#995]
I am unable to position two DeckGLMap components side by side in the same page. 

This is the code I am using to layout the two components:
```
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr",}}>
      <div style={{ height: "100vh", background: "green", position: "relative"}}>
        <DeckGLMap layers={args.layers} />
      </div>
      <div style={{ height: "100vh", background: "blue", position: "relative"}}>
        <DeckGLMap layers={args.layers} />
      </div>
    </div>
```
![image](https://user-images.githubusercontent.com/18436935/168750486-ab325db3-df71-4d60-a179-7fe85bd80199.png)
There are a few issues with this layout: 
1. The scale bar is not position correctly in the component
2. There is an unwanted padding around the component
3. A scroll bar is introduced 

If I do not supply height to the containing div component then I get:
![image](https://user-images.githubusercontent.com/18436935/168751337-37d08a51-2af6-43fe-9ec2-223f6b379c0e.png)

And if I don't use position: "relative"  in the containing div then both component canvases overlap and I am only able to control the top one.

**Comment by shadab-skhan** [comment]
The deckGL component is positioned as absolute by default, in order to position it correctly, it should be position relatively in a parent div. And for height, it's a known issue across deckGL community for using it with relative positioning, a height need to be passed.

A padding of 1rem is added by storybook and hence the scrollbar appears. It should be consumer's responsibility to handle this.
